#!/bin/bash
# One-command pipeline: train PPO, train DQN, then evaluate twice --
# once with the best (load-normalized BP) checkpoints and once with the
# final-episode checkpoints. Run from anywhere; it cd's to the repo root.
#
# Foreground:   bash run_all.sh
# Background:   nohup bash run_all.sh > run_all.log 2>&1 &
#               tail -f run_all.log
#
# Every log and xlsx is stamped with the start time, so reruns never
# overwrite earlier results. To skip DQN, comment out the [2/4] block.

set -e
cd "$(dirname "$0")"

PY=$(command -v python3 || command -v python)
CONFIG=examples/example_config.py
CKPT_DIR=examples/checkpoints
STAMP=$(date +%Y%m%d_%H%M%S)

echo "=== [1/4] Training PPO ($STAMP) ==="
$PY -m training.simulator train --config $CONFIG --agent PPO 2>&1 | tee "training_PPO_$STAMP.log"
mv -f "$CKPT_DIR/training_results.xlsx" "$CKPT_DIR/training_results_PPO_$STAMP.xlsx"

echo "=== [2/4] Training DQN ==="
$PY -m training.simulator train --config $CONFIG --agent DQN 2>&1 | tee "training_DQN_$STAMP.log"
mv -f "$CKPT_DIR/training_results.xlsx" "$CKPT_DIR/training_results_DQN_$STAMP.xlsx"

echo "=== [3/4] Testing 1/2: BEST checkpoints ==="
$PY -m training.simulator evaluate --config $CONFIG --methods PPO DQN FF RF 2>&1 | tee "evaluate_best_$STAMP.log"
mv -f "$CKPT_DIR/evaluation_results.xlsx" "$CKPT_DIR/evaluation_results_best_$STAMP.xlsx"

echo "=== [4/4] Testing 2/2: FINAL-episode checkpoints ==="
# Same config, but checkpoint_path pointed at the <name>_final base that
# training now always saves (see training/simulator.py).
cat > examples/_final_eval_config.py <<'PYEOF'
"""Auto-generated by run_all.sh: evaluate the final-episode checkpoints."""
import dataclasses
import importlib.util
import os

_HERE = os.path.dirname(os.path.abspath(__file__))
_spec = importlib.util.spec_from_file_location("_base_config", os.path.join(_HERE, "example_config.py"))
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)


def build_config():
    cfg = _mod.build_config()
    training = dataclasses.replace(cfg.training, checkpoint_path=cfg.training.checkpoint_path + "_final")
    return dataclasses.replace(cfg, training=training)
PYEOF
$PY -m training.simulator evaluate --config examples/_final_eval_config.py --methods PPO DQN FF RF 2>&1 | tee "evaluate_final_$STAMP.log"
mv -f "$CKPT_DIR/evaluation_results.xlsx" "$CKPT_DIR/evaluation_results_final_$STAMP.xlsx"

echo "======================================================================"
echo "ALL DONE ($STAMP). Result files:"
ls -l "$CKPT_DIR"/*"$STAMP"*.xlsx
echo "Logs: training_PPO_$STAMP.log training_DQN_$STAMP.log evaluate_best_$STAMP.log evaluate_final_$STAMP.log"
